RickyFeliguete/Models/AccountModels/AvailableUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RickyFeliguete.Models.AccountModels
{
    public class AvailableUser
    {
        [Required(ErrorMessage = "Digite um nome de usuário")]
        [Display(Name = "Nome de Usuário")]
        [RegularExpression(@"^[a-zA-Za]*$", ErrorMessage = "Caracteres especiais não são permitidos")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Digite uma senha")]
        [StringLength(10, ErrorMessage = "O tamanho máximo de caracteres é {1} e o mínimo é {2}", MinimumLength = 6)]
        [Display(Name = "Senha")]
        public string UserPassword { get; set; }
        [Display(Name = "Nome completo")]
        public string FullName { get; set; }

        public static List<AvailableUser> AllUsers()
        {
            List<AvailableUser> userList = new List<AvailableUser>();

            AvailableUser user1 = new AvailableUser
            {
                UserName = "Anupam Das",
                UserPassword = "lifeisbeautiful",
                FullName = "Life is Beautiful"
            };

            AvailableUser user2 = new AvailableUser
            {
                UserName = "Chinmoy Das",
                UserPassword = "GoodTime",
                FullName = "Good Time"
            };

            userList.Add(user1);
            userList.Add(user2);

            return userList;
        }
    }
}

RickyFeliguete/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RickyFeliguete.Models;

namespace RickyFeliguete.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AvailableUserList()
        {
            ViewBag.Text = "Controller Text";
            return View(Models.AccountModels.AvailableUser.AllUsers());
        }
    }
}

RickyFeliguete/Controllers/AvailableUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RickyFeliguete.Models.AccountModels;
using System.ComponentModel.DataAnnotations;

namespace RickyFeliguete.Controllers
{
    public class AvailableUsersController : Controller
    {
        // GET: AvailableUsers
        public ActionResult Index()
        {
            return View();
        }

        // GET: AvailableUsers/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AvailableUsers/Create
        public ActionResult Create()
        {
            AvailableUser usr = new AvailableUser();
            return View(usr);
        }

        // POST: AvailableUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public string Create(AvailableUser usr)
        //public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                //return RedirectToAction("Index");
                // return "nome de usuario = " + usr.UserName + "; senha = " + usr.UserPassword + "; nome completo = " + usr.FullName;

                if (ModelState.IsValid)
                {
                    return "nome de usuario = " + usr.UserName + "; senha = " + usr.UserPassword + "; nome completo = " + usr.FullName;
                }
                else
                    return null;
            }
            catch
            {
                return "erro";
                //return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: AvailableUsers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AvailableUsers/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AvailableUsers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AvailableUsers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login()
        {

            ViewBag.Title = "Login";
            return View(new AvailableUser());
        }

        [HttpPost]
        public string Login(AvailableUser user)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Title = "Testing Login action";
                ViewBag.UserName = user.FullName;
                return ViewBag.Title + ViewBag.UserName;
            }
            else{
                return "Validação no servidor falhou";
            }
            return null;
        }
    }
}

RickyFeliguete/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RickyFeliguete.Controllers
{
    public class HomeController : Controller
    {

        //comentário feliguete - forçando conflito

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RickyFeliguete/Views/AvailableUsers/Create.cshtml
@model RickyFeliguete.Models.AccountModels.AvailableUser

@{
    ViewBag.Title = "Create User - Ricky";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@*@using (Html.BeginForm("Lagartixa", "AvailableUsers", FormMethod.Post))*@
@using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AvailableUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "seu nome"} })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.UserPassword, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control", @placeholder = "sua senha" } )
                @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @placeholder = "nome completo" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

RickyFeliguete/Views/AvailableUsers/Login.cshtml
@model RickyFeliguete.Models.AccountModels.AvailableUser

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    
    <div class="form-horizontal">

        <div class="form-group">
            <label>User Name</label>
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nome" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label>Password</label>
            @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.UserPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    <br />
    <p>
        @Html.ActionLink("New user? Sign up here!", "Create", "AvailableUsers")
    </p>
    <style type="text/css">
        .input-validation-error{
            background-color:darksalmon;
        }
    </style>
}
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

RickyFeliguete/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RickyFeliguete/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RickyFeliguete/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

RickyFeliguete/Views/Shared/_DisplayAllUsers.cshtml
@foreach (var usr in AvailableUser)
{
    <text>
        @usr.UserName  @usr.UserPassword <br />
    </text>
}

RickyFeliguete/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <a href="~/Views/Shared/_Layout.cshtml">~/Views/Shared/_Layout.cshtml</a>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("User List", "AvailableUserList", "Account")</li>
                    <li>@Html.ActionLink("Create Users", "Create", "AvailableUsers")</li> <!-- link no topo da página para criação de usuários :: Ricky -->

                    <li>@Html.ActionLink("Login", "Login", "AvailableUsers")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RickyFeliguete/Views/Shared/_StaticRenderPage.cshtml
<p>
    This message is from Render Page.
    @RenderBody()
</p>